# <a id="inicio"></a> Knight's Tour

-----

### **Autores:** Glauco, 

-----

## <a id="resumo"></a> Resumo 

Este relatório descreve uma modelagem do famoso problema do "Knight's Tour". O problema envolve movimentar um cavalo em um tabuleiro de xadrez, garantindo que o cavalo visite cada quadrado uma única vez.

## <a id="sumario"></a> Sumário


* [Início](#inicio)
* [Resumo](#resumo)
* [Sumário](#sumario)
* [Espaço de Estado](#espaco_estado)
* [Estados Iniciais](#estados_iniciais)
* [Estado Objetivo](#estado_objetivo)
* [Ações Disponíveis](#acoes_disp)
* [Modelo do Problema](#modelo_problema)
* [Resultados](#resultados)

## <a id="espaco_estado"></a> Espaço de Estado

O espaço de estado para esse problema consiste em representar todas as possíveis configurações do tabuleiro de xadrez conforme o cavalo se move de um quadrado para outro. Casa com valor zero ainda não tiveram o cavalo na sua posição, casa com valor 1 já recebeu o cavalo uma vez.

Por se tratar de um tabuleiro de xadrez, por exemplo 8x8, um estado possível do espaço de estado pode ser representado como:

In [253]:
import numpy as np
tabuleiro = np.zeros((8, 8), dtype=int)
tabuleiro[0][3] = 1
tabuleiro[2][2] = 2
print(tabuleiro)

[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Nesse caso o cavalo estava ocupando a quarta coluna da primeira linha e depois parou na terceira coluna da terceira linha.

O número total de possíveis valores no espaço de estado para o problema pode ser calculado por 2 elevado a 64 (8x8), sendo igual a 1.8446744e+19 estados. Logo seria inviável listar todos seus valores.

## <a id="estados_iniciais"></a> Estados Iniciais

Os estados iniciais para esse problema pode ser qualquer uma das 64 casas disponíveis no tabuleiro de exemplo. De forma a automatizar isso foi criada uma função que inicializa um tabuleiro com o estado inicial e tamanho fornecido pelo usuário. Também foi criada uma função para printar de forma agradável o tabuleiro.

In [254]:
from tabulate import tabulate
from colorama import Fore, Style


def inicializa_tabuleiro(linha, coluna, tamanho=8):
    tabuleiro = np.zeros((tamanho, tamanho), dtype=int)
    tabuleiro[linha][coluna] = 1
    return tabuleiro


def print_tabuleiro(tabuleiro):
    headers = [f"Coluna {col}" for col in range(len(tabuleiro[0]))]
    rows = [[f"Linha {i}"] + [str(cell) for cell in row] for i, row in enumerate(tabuleiro)]
    for row in rows:
        for j, cell in enumerate(row):
            if cell > '0' and j > 0:
                row[j] = f"{Fore.GREEN}{cell}{Style.RESET_ALL}"
            if cell == '0':
                row[j] = f"{Fore.RED}{cell}{Style.RESET_ALL}"
    print(tabulate(rows, headers=headers, tablefmt="grid"))

In [255]:
tabuleiro_inicial = inicializa_tabuleiro(2,2)
print("Estado inicial exemplo 1")
print_tabuleiro(tabuleiro_inicial)

Estado inicial exemplo 1
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
|         |   Coluna 0 |   Coluna 1 |   Coluna 2 |   Coluna 3 |   Coluna 4 |   Coluna 5 |   Coluna 6 |   Coluna 7 |
+=========+============+============+============+============+============+============+============+============+
| Linha 0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
| Linha 1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
| Linha 2 |          0 |          0 |          1 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+----------

In [256]:
tabuleiro_inicial = inicializa_tabuleiro(5,6)
print("Estado inicial exemplo 2")
print_tabuleiro(tabuleiro_inicial)

Estado inicial exemplo 2
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
|         |   Coluna 0 |   Coluna 1 |   Coluna 2 |   Coluna 3 |   Coluna 4 |   Coluna 5 |   Coluna 6 |   Coluna 7 |
+=========+============+============+============+============+============+============+============+============+
| Linha 0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
| Linha 1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
| Linha 2 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+----------

## <a id="estado_objetivo"></a> Estado Objetivo

O estado objetivo é quando o cavalo já tenha passado em todas as casa uma única vez, ficando o tabuleiro da seguinte maneira.

In [257]:
tabuleiro_objetivo = [[1, 6, 15, 10, 21],
                      [14, 9, 20, 5, 16],
                      [19, 2, 7, 22, 11],
                      [8, 13, 24, 17, 4],
                      [25, 18, 3, 12, 23]
                    ]

print("Estado Objetivo")
print_tabuleiro(tabuleiro_objetivo)

Estado Objetivo
+---------+------------+------------+------------+------------+------------+
|         |   Coluna 0 |   Coluna 1 |   Coluna 2 |   Coluna 3 |   Coluna 4 |
+=========+============+============+============+============+============+
| Linha 0 |          1 |          6 |         15 |         10 |         21 |
+---------+------------+------------+------------+------------+------------+
| Linha 1 |         14 |          9 |         20 |          5 |         16 |
+---------+------------+------------+------------+------------+------------+
| Linha 2 |         19 |          2 |          7 |         22 |         11 |
+---------+------------+------------+------------+------------+------------+
| Linha 3 |          8 |         13 |         24 |         17 |          4 |
+---------+------------+------------+------------+------------+------------+
| Linha 4 |         25 |         18 |          3 |         12 |         23 |
+---------+------------+------------+------------+----------

## <a id="acoes_disp"></a> Ações Disponíveis

O conjunto de operadores que descreva as ações disponíveis segue as regras do Xadrez, que no caso o cavalo é uma peça que anda em formato de L, duas casas para um lado e depois uma à 90 graus ou uma casa para um lado e as outras duas à 90 graus. O conjunto de todos esses movimentos são encontrados abaixo:

In [258]:
conjunto_operadores = [
    (2, 1),   # v v >

    (2, -1),  # v v <

    (-2, 1),  # ^ ^ >

    (-2, -1), # ^ ^ <
    
    (1, 2),   # v > >

    (1, -2),  # v < <

    (-1, 2),  # ^ > >

    (-1, -2)  # ^ < <
]

Outro fator que limita as ações disponíveis é se a casa de destino ainda não foi visitada, se por algum motivo ela já tenha recebido o cavalo, ela não poderá receber novamente. O problema acaba quando o número de movimentos é igual ao número de casas do tabuleiro.

Com essas informações pode-se montar uma função que verifica se o cavalo pode ou não fazer um certo movimento. E quando identificar que ele terminou o problema.

In [259]:
def movimento_ok(tabuleiro, operador, origem):
    linha_destino = origem[0] + operador[0]
    coluna_destino = origem[1] + operador[1]
    if 0 <= linha_destino < len(tabuleiro) and 0 <= coluna_destino < len(tabuleiro) and tabuleiro[linha_destino][coluna_destino] == 0:
        return True
    else:
        return False


def problema_finalizado(numero_movimento,tamanho=8):
    return numero_movimento == tamanho*tamanho

## <a id="modelo_problema"></a> Modelo do Problema

Para resolver o problema do "Knight's Tour" utilizaremos a busca em profundidade para explorar todas as possíveis sequências de movimentos do cavalo até encontrar uma solução que cubra todos os quadrados do tabuleiro exatamente uma vez.

In [260]:
def busca_em_profundidade(linha, coluna, tabuleiro, numero_movimento):
    tabuleiro[linha][coluna] = numero_movimento

    if problema_finalizado(numero_movimento, len(tabuleiro)):
        return True, tabuleiro

    for operador in conjunto_operadores:
        nova_linha = linha + operador[0]
        nova_coluna = coluna + operador[1]

        if movimento_ok(tabuleiro, operador, (linha, coluna)) and busca_em_profundidade(nova_linha, nova_coluna, tabuleiro, numero_movimento + 1)[0]:
            return True, tabuleiro

    tabuleiro[linha][coluna] = 0
    return False, tabuleiro

def resolver_problema(tamanho=8, linha_inicial=0, coluna_inicial=0):
    tabuleiro = inicializa_tabuleiro(linha_inicial, coluna_inicial, tamanho)
    solucao, tabuleiro = busca_em_profundidade(linha_inicial, coluna_inicial, tabuleiro, 1)

    if not solucao:
        print("Não há solução possível.")
    else:
        print("Problema Resolvido!")
        print_tabuleiro(tabuleiro)



## <a id="resultados"></a> Resultados

Com o modelo acima desenvolvido foram executados alguns cenários para validação:


### Tabuleiro inteiro 7x7 com início em 0,0

In [262]:
resolver_problema(tamanho=7, linha_inicial=0, coluna_inicial=0)

Problema Resolvido!
+---------+------------+------------+------------+------------+------------+------------+------------+
|         |   Coluna 0 |   Coluna 1 |   Coluna 2 |   Coluna 3 |   Coluna 4 |   Coluna 5 |   Coluna 6 |
+=========+============+============+============+============+============+============+============+
| Linha 0 |          1 |         28 |         37 |         40 |         25 |         30 |          9 |
+---------+------------+------------+------------+------------+------------+------------+------------+
| Linha 1 |         38 |         41 |         26 |         29 |         10 |         35 |         24 |
+---------+------------+------------+------------+------------+------------+------------+------------+
| Linha 2 |         27 |          2 |         39 |         36 |         23 |          8 |         31 |
+---------+------------+------------+------------+------------+------------+------------+------------+
| Linha 3 |         42 |         19 |         44 |   

### Tabuleiro 5x5 com início em 2,3

In [263]:
resolver_problema(tamanho=5, linha_inicial=2, coluna_inicial=3)

Não há solução possível.
