# <a id="inicio"></a> Knight's Tour

-----

### **Autores:** Glauco, 

-----

## <a id="resumo"></a> Resumo 

Este relatório descreve uma modelagem do famoso problema do "Knight's Tour". O problema envolve movimentar um cavalo em um tabuleiro de xadrez, garantindo que o cavalo visite cada quadrado uma única vez.

## <a id="sumario"></a> Sumário


* [Início](#inicio)
* [Resumo](#resumo)
* [Sumário](#sumario)
* [Espaço de Estado](#espaco_estado)
* [Estados Iniciais](#estados_iniciais)
* [Estado Objetivo](#estado_objetivo)


## <a id="espaco_estado"></a> Espaço de Estado

O espaço de estado para esse problema consiste em representar todas as possíveis configurações do tabuleiro de xadrez conforme o cavalo se move de um quadrado para outro.

Por se tratar de um tabuleiro de xadrez 8x8, um estado possível do espaço de estado pode ser representado como:

In [37]:
import numpy as np
tabuleiro = np.zeros((8, 8), dtype=int)
tabuleiro[0][3] = 1
tabuleiro[2][2] = 1
print(tabuleiro)

[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Nesse caso o cavalo estava ocupando a quarta coluna da primeira linha e depois parou na terceira coluna da terceira linha.

O número total de possíveis valores no espaço de estado para o problema pode ser calculado por 2 elevado a 64 (8x8), sendo igual a 1.8446744e+19 estados. Logo seria inviável listar todos seus valores.

## <a id="estados_iniciais"></a> Estados Iniciais

Os estados iniciais para esse problema pode ser qualquer uma das 64 casas disponíveis no tabuleiro. De forma a automatizar isso foi criada uma função que inicializa um tabuleiro com o estado inicial fornecido pelo usuário. Também foi criada uma função para printar de forma agradável o tabuleiro.

In [38]:
from tabulate import tabulate
from colorama import Fore, Style


def inicializa_tabuleiro(linha, coluna):
    tabuleiro = np.zeros((8, 8), dtype=int)
    tabuleiro[linha][coluna] = 1
    return tabuleiro


def print_tabuleiro(tabuleiro):
    headers = [f"Coluna {col}" for col in range(len(tabuleiro[0]))]
    rows = [[f"Linha {i}"] + [str(cell) for cell in row] for i, row in enumerate(tabuleiro)]
    for row in rows:
        for j, cell in enumerate(row):
            if cell == '1':
                row[j] = f"{Fore.GREEN}{cell}{Style.RESET_ALL}"
            if cell == '0':
                row[j] = f"{Fore.RED}{cell}{Style.RESET_ALL}"
    print(tabulate(rows, headers=headers, tablefmt="grid"))

In [39]:
tabuleiro_inicial = inicializa_tabuleiro(2,2)
print("Estado inicial exemplo 1")
print_tabuleiro(tabuleiro_inicial)

Estado inicial exemplo 1
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
|         |   Coluna 0 |   Coluna 1 |   Coluna 2 |   Coluna 3 |   Coluna 4 |   Coluna 5 |   Coluna 6 |   Coluna 7 |
+=========+============+============+============+============+============+============+============+============+
| Linha 0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
| Linha 1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
| Linha 2 |          0 |          0 |          1 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+----------

In [40]:
tabuleiro_inicial = inicializa_tabuleiro(5,6)
print("Estado inicial exemplo 2")
print_tabuleiro(tabuleiro_inicial)

Estado inicial exemplo 2
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
|         |   Coluna 0 |   Coluna 1 |   Coluna 2 |   Coluna 3 |   Coluna 4 |   Coluna 5 |   Coluna 6 |   Coluna 7 |
+=========+============+============+============+============+============+============+============+============+
| Linha 0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
| Linha 1 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
| Linha 2 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
+---------+------------+------------+----------

## <a id="estado_objetivo"></a> Estado Objetivo

O estado objetivo é quando o cavalo já tenha passado em todas as casa uma única vez, ficando o tabuleiro da seguinte maneira.

In [41]:
tabuleiro_objetivo = np.ones((8, 8), dtype=int)
print("Estado Objetivo")
print_tabuleiro(tabuleiro_objetivo)

Estado Objetivo
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
|         |   Coluna 0 |   Coluna 1 |   Coluna 2 |   Coluna 3 |   Coluna 4 |   Coluna 5 |   Coluna 6 |   Coluna 7 |
+=========+============+============+============+============+============+============+============+============+
| Linha 0 |          1 |          1 |          1 |          1 |          1 |          1 |          1 |          1 |
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
| Linha 1 |          1 |          1 |          1 |          1 |          1 |          1 |          1 |          1 |
+---------+------------+------------+------------+------------+------------+------------+------------+------------+
| Linha 2 |          1 |          1 |          1 |          1 |          1 |          1 |          1 |          1 |
+---------+------------+------------+------------+------